name: 'GitHub Readme QotD'
author: 'Larry Huynh'
description: 'GitHub Actions workflow to automate your repo Readme update with a dynamic Quote of the Day section.'

inputs:
  TOKEN:
    required: true
    default: ${{ github.token }}
  REPO:
    required: false
    default: ${{ github.repository }}

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'type'
  color: 'gray-dark'
